runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- node_modules/

handlers:
- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /build
  static_dir: build
  secure: always

- url: /data
  static_dir: data
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /src
  static_dir: src
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /package.json
  static_files: package.json
  upload: package.json
  secure: always

- url: /polymer.json
  static_files: polymer.json
  upload: polymer.json
  secure: always

- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js
  secure: always

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  secure: always
