runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- node_modules/

handlers:

- url: /bower_components
  static_dir: build/es6-unbundled/bower_components
  secure: always

- url: /images
  static_dir: build/es6-unbundled/images
  secure: always

- url: /src
  static_dir: build/es6-unbundled/src
  secure: always

- url: /manifest.json
  static_files: build/es6-unbundled/manifest.json
  upload: build/es6-unbundled/manifest.json
  secure: always

- url: /push-manifest.json
  static_files: build/es6-unbundled/push-manifest.json
  upload: build/es6-unbundled/push-manifest.json
  secure: always

- url: /sw.js
  static_files: build/es6-unbundled/sw.js
  upload: build/es6-unbundled/sw.js
  secure: always

- url: /.*
  static_files: build/es6-unbundled/index.html
  upload: build/es6-unbundled/index.html
  secure: always
