
version: 2
jobs:
  build:
    docker:

      - image: circleci/node:7.10-browsers
      - image: google/cloud-sdk

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: bower install

      - save_cache:
          paths:
            - node_modules
            - bower_components
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - deploy:
         name: Deploy Master to GKE
         command: |
           if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd build && npm install && cd ..
             ./deploy.sh
           fi
